### ISSUE TITLE
Tests estadísticos

### ISSUE THREAD

**Issue by amarrerod** [Tomas-Morph/MenuPlanning_MOEAD_Mathematics#1]
En esta parte del código para generar las tablas, ¿siempre consideramos minimización o depende del problema? Porque para el problema de la mochila que tenemos ahora estamos maximizando y habría que cambiar las comparaciones ¿no?

https://github.com/Tomas-Morph/MenuPlanning_MOEAD_Mathematics/blob/05844791576830c587c71bb1a85f5aaf17939f8e/scripts/statisticalTests_old.pl#L221-L234

**Comment by esegredo** [comment]
@amarrerod La línea 221 siempre hay que mantenerla, dado que siempre es necesario que el p-value sea menor que el nivel de significación para que existan diferencias estadísticas significativas.

Creo que solo tendrías que invertir la comparación de la línea 226, dado que las anteriores significan que una de las muestras tenga menor media y mayor mediana y la otra muestra lo contrario, por lo que no podríamos discriminar por media y mediana, sino solo por una de ellas (o bien media, o bien mediana).
